### ISSUE TITLE
about TextView window 

### ISSUE THREAD

**Issue by zhangkangbin** [yangxu4536/MeiTuanLocateCity#2]
09-09 02:17:49.375  27648-27648/com.testapp E/WindowManager﹕ Activity com.test.app.Ctiy has leaked window android.widget.TextView@53840b7c that was originally added here
    android.view.WindowLeaked: Activity com.didi.app.Ctiy has leaked window android.widget.TextView@53840b7c that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:374)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:292)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:224)
            at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:149)
            at android.view.Window$LocalWindowManager.addView(Window.java:547)
            at com.didi.app.Ctiy.initOverlay(Ctiy.java:702)
            at com.didi.app.Ctiy.onCreate(Ctiy.java:169)
            at android.app.Activity.performCreate(Activity.java:5008)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
            at android.app.ActivityThread.access$600(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

这是关闭了activity 出现的问题。。

我在 onDestroy移除了这个textview 就不报错了。

  windowManager.removeView(overlay); //移除窗口

**Comment by zhangkangbin** [comment]
我不知道这样的做法是否正确。。
